### ISSUE TITLE
whatever I do I get {   "error": "no response from server" }

### ISSUE THREAD

**Issue by depsterr** [Pupix/rift-explorer#41]
I would like to prefix by saying my knowledge is very limited within JSON and the like, I am simply trying to change my profile picture like many others.

After trying to use the different tools in the rift-explorer executable all that happens is that I get `Response Headers`
`{
  "error": "no response from server"
}`

screenshot: https://imgur.com/0qCO1Lg

I am running league 9.10 and I don't think I have anything else running that would interfere.

**Comment by I3lack03** [comment]
Same issue. Has nothing to do with recent Windows Updates, already tried. :/

**Comment by ezx223** [comment]
I can't even open Rift Explorer, because putting Enable_swagger in System doesn't work anymore, how did you do it ??

**Comment by I3lack03** [comment]
I can open it. It then proceeds to ask for a restart of Lol in order to get the API documentation. When I do that, League starts to repair and sometimes I get in, sometimes Rift Explorer just give me the message to restart League. Even when I get in, it doesnt work and I get the message :"{ "error": "no response from server"". 
The Programm still works for some of my friends, for others not. :/

**Comment by Pupix** [comment]
Same problem as #36 
Workaround and Riot's stance on it here https://github.com/RiotGames/developer-relations/issues/117

**Comment by Pupix** [comment]
This has been fixed in [v6.0.0](https://github.com/Pupix/rift-explorer/releases/tag/v6.0.0). Try it out and let me know if it's working for you.
