### ISSUE TITLE
Is there an API to get live game info?

### ISSUE THREAD

**Issue by tuananhtd** [Pupix/rift-explorer#5]
I know that the public Riot Api does have this but unfortunately it's only available for Riot managed regions. I'm wondering how we can get the current game ID / dropInSpectateGameId from Summoner ID/ name?

**Comment by be90728** [comment]
/lol-gameflow/v1/session

**Comment by Pupix** [comment]
Most of the League client works with the currently logged in account, ot with random summoner IDs/names. Unless Riot changed their policy, if someone's not on your friend list you can't really get much data from them.

You can get the current game ID of yourself from the lol-gameflow API `GET /lol-gameflow/v1/session`.

```json
{
  ...
  "gameData": {
    "gameId": 3440794724
  ...
  }
    ...
}
```

Otherwise you can use the `GET /lol-chat/v1/friends/{id}` and see if they are in a game or not. To launch the spectator for one of your friend's game client use `POST /lol-gameflow/v1/spectate/launch`.
